name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: zbHiFuvAE_bmP_FguFdQKV7LUTq35_oe70ATxlPt
          accountId: f6ab62605dfa09f1763603f2d8a1c6f6
          command: deploy --env production --minify src/index.js
          environment: production
